### ISSUE TITLE
Docker support please

### ISSUE THREAD

**Issue by arsaboo** [shaunthecomputerscientist/EDA-GPT#4]
Can you please provide docker support...thanks!

**Comment by shaunthecomputerscientist** [comment]
If you want me to make a package which supports structured data analysis i can do that. Or maybe since there are dependency issues i can dockerize it and make a web app for that like Julius ai. The problem is i am not getting time these days. If anyone wants to work on this with me I'll explain the project.

**Comment by qwaszaq** [comment]
be nice to get a docker!

**Comment by shaunthecomputerscientist** [comment]
> be nice to get a docker!

 I am a little busy right now. Give me some time. I will try to dockerize the app. Or release a package which provides similar functions.

**Comment by shaunthecomputerscientist** [comment]
> Can you please provide docker support...thanks!

Added docker support and instructions in readme.

**Comment by arsaboo** [comment]
I ran it using the following compose file, but it is not working. 
```yaml
services:
  eda_gpt_service:
    image: mrpoldockeroperator123/eda-gpt:v1
    container_name: eda_gpt
    ports:
      - "8502:8501"
    restart: always
    environment:
      - TZ=America/New_York
```
I see the following error in the docker logs:
```bash
Error: Invalid value: File does not exist: home.py
Usage: streamlit run [OPTIONS] TARGET [ARGS]...
Try 'streamlit run --help' for help.
```

**Comment by arsaboo** [comment]
Even with `docker run -d -p 8501:8501 mrpoldockeroperator123/eda-gpt:v1`, I get the same error:
```bash
Usage: streamlit run [OPTIONS] TARGET [ARGS]...
Try 'streamlit run --help' for help.
Error: Invalid value: File does not exist: home.py
```

Looks like the home.py needs to be moved to the right folder @shaunthecomputerscientist

**Comment by shaunthecomputerscientist** [comment]
> Even with `docker run -d -p 8501:8501 mrpoldockeroperator123/eda-gpt:v1`, I get the same error:
> ```bash
> Usage: streamlit run [OPTIONS] TARGET [ARGS]...
> Try 'streamlit run --help' for help.
> Error: Invalid value: File does not exist: home.py
> ```
> 
> Looks like the home.py needs to be moved to the right folder @shaunthecomputerscientist 

Did you download docker desktop?

**Comment by shaunthecomputerscientist** [comment]
I think the problem is related to home.py. The filename is Home.py. It seems to be case-sensitive.

**Comment by arsaboo** [comment]
> Did you download docker desktop?

I tried this on Ubuntu and Mac (where I have docker desktop).

**Comment by shaunthecomputerscientist** [comment]
> > Did you download docker desktop?
> 
> I tried this on Ubuntu and Mac (where I have docker desktop). 

Added new version check the docker try to run the container. Version v2.

**Comment by arsaboo** [comment]
@shaunthecomputerscientist Tried v2, and I can see the UI, but a couple of things:
First, I see this error:
```bash
2024-08-25 09:42:35.996 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "/app/pages/EDA_GPT.py", line 3, in <module>
    from pages.src.unstructured_data import unstructured_Analyzer
  File "/app/pages/src/unstructured_data.py", line 4, in <module>
    from .vstore import VectorStore
  File "/app/pages/src/vstore.py", line 15, in <module>
    from unstructured.partition.auto import partition_pdf
  File "/usr/local/lib/python3.11/site-packages/unstructured/partition/auto.py", line 83, in <module>
    from unstructured.partition.pdf import partition_pdf
  File "/usr/local/lib/python3.11/site-packages/unstructured/partition/pdf.py", line 50, in <module>
    from unstructured.partition.pdf_image.pdf_image_utils import (
  File "/usr/local/lib/python3.11/site-packages/unstructured/partition/pdf_image/pdf_image_utils.py", line 13, in <module>
    import cv2
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
```

Second, where is the secret.toml file? I did not see any mount path in the docker command.

**Comment by shaunthecomputerscientist** [comment]
> @shaunthecomputerscientist Tried v2, and I can see the UI, but a couple of things:
> First, I see this error:
> ```bash
> 2024-08-25 09:42:35.996 Uncaught app exception
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
>     result = func()
>              ^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
>     exec(code, module.__dict__)
>   File "/app/pages/EDA_GPT.py", line 3, in <module>
>     from pages.src.unstructured_data import unstructured_Analyzer
>   File "/app/pages/src/unstructured_data.py", line 4, in <module>
>     from .vstore import VectorStore
>   File "/app/pages/src/vstore.py", line 15, in <module>
>     from unstructured.partition.auto import partition_pdf
>   File "/usr/local/lib/python3.11/site-packages/unstructured/partition/auto.py", line 83, in <module>
>     from unstructured.partition.pdf import partition_pdf
>   File "/usr/local/lib/python3.11/site-packages/unstructured/partition/pdf.py", line 50, in <module>
>     from unstructured.partition.pdf_image.pdf_image_utils import (
>   File "/usr/local/lib/python3.11/site-packages/unstructured/partition/pdf_image/pdf_image_utils.py", line 13, in <module>
>     import cv2
> ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
> ```
> 
> Second, where is the secret.toml file? I did not see any mount path in the docker command. 

Shit again. I shouldn't have used streamlit. I will check it. My exam gets over on 1st. I will be able to work on this from then on. Would you like to help me to make a proper image?

**Comment by arsaboo** [comment]
I wish I knew. I can test things out, but I don't know how to create an image. I would like to use it with Ollama locally. 

Please focus on the exam for now...we can wait until after your exams.

**Comment by shaunthecomputerscientist** [comment]
> I wish I knew. I can test things out, but I don't know how to create an image. I would like to use it with Ollama locally. 
> 
> Please focus on the exam for now...we can wait until after your exams. 

Thank you but i will get it fixed in some time. Also when i am checking the image in a container i see that secrets.toml is present. What's the size of this image btw? To confirm.

**Comment by arsaboo** [comment]
My question is more about how do I edit the secrets.toml. Here's the docker-compose that I am using:

```yaml
services:
  eda_gpt_service:
    image: mrpoldockeroperator123/eda-gpt:v2
    container_name: eda_gpt
    ports:
      - "8501:8501"
    restart: always
    environment:
      - TZ=America/New_York
```

**Comment by shaunthecomputerscientist** [comment]
You need to use the terminal in docker and since it's a linux system you need to use bash commands to navigate then see the file then update it.

But the app is throwing error as it starts right?

docker exec -it <container_id_or_name> /bin/bash

You can access container shell like this.

Then move to secrets.toml step by step.

**Comment by arsaboo** [comment]
The container starts....I am seeing that error here:
![image](https://github.com/user-attachments/assets/07602ffa-2a11-422c-91c7-0a76392c29ee)

BTW, I was able to use the shell to access the secrets.toml (we may want to move things to env, as is typically the case). I don't see any setting for Ollama there.

**Comment by shaunthecomputerscientist** [comment]
> The container starts....I am seeing that error here:
> ![image](https://github.com/user-attachments/assets/07602ffa-2a11-422c-91c7-0a76392c29ee)
> 
> BTW, I was able to use the shell to access the secrets.toml (we may want to move things to env, as is typically the case). I don't see any setting for Ollama there. 

I will get back to this in a week. I did not the containers myself. I delete it since i have less space. I will test it out and update documentation.

**Comment by ShahzaibAnwar** [comment]
> > The container starts....I am seeing that error here:
> > ![image](https://private-user-images.githubusercontent.com/18319734/361246726-07602ffa-2a11-422c-91c7-0a76392c29ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NjI2MTIsIm5iZiI6MTcyODU2MjMxMiwicGF0aCI6Ii8xODMxOTczNC8zNjEyNDY3MjYtMDc2MDJmZmEtMmExMS00MjJjLTkxYzctMGE3NjM5MmMyOWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDEyMTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NmNiNjg3NTI4NjUyMTJiNWQzZTkxYWU0MWE1ODQxOWFiOTUyMGVhYzYxZTZiMDllYTJiODE3OGNhOTFjMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RCBG4MN-r7z9EmS_3VXRzO19eDlbk2o0x0QwxVgIXcM)
> > BTW, I was able to use the shell to access the secrets.toml (we may want to move things to env, as is typically the case). I don't see any setting for Ollama there.
> 
> I will get back to this in a week. I did not the containers myself. I delete it since i have less space. I will test it out and update documentation.

Hi, Any update as i am facing the same issue, 

![Screenshot 2024-10-10 171117](https://github.com/user-attachments/assets/5e5e8301-96d6-4385-ba41-cf65b67885f8)
